apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: game-store
type: Opaque
data:
  JWT_SECRET: eW91ci1zZWNyZXQta2V5  # base64 encoded "your-secret-key"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
type: Opaque
data:
  admin-user: YWRtaW4=  # base64 encoded "admin"
  admin-password: YWRtaW4xMjM=  # base64 encoded "admin123" 