apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  namespace: gameportal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
      - name: authentication
        image: auth-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: JWT_SECRET
          value: "your-secret-key-for-testing"
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-svc
  namespace: gameportal
spec:
  selector:
    app: authentication
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP