apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: gameportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        ports:
        - containerPort: 27017
        command: ["mongod", "--noauth", "--bind_ip_all"]
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: gameportal
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
  namespace: gameportal
data:
  init.js: |
    // Switch to gameportal database
    db = db.getSiblingDB('gameportal');
    
    // Create the gameportal user
    db.createUser({
      user: 'gameportal',
      pwd: 'password123',
      roles: [
        {
          role: 'readWrite',
          db: 'gameportal'
        }
      ]
    });
    
    print('User gameportal created successfully');
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: gameportal
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-external
  namespace: gameportal
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: LoadBalancer
