apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-catalog
  namespace: gameportal
  labels:
    app: game-catalog
    tier: backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: game-catalog
  template:
    metadata:
      labels:
        app: game-catalog
        tier: backend
    spec:
      containers:
      - name: game-catalog
        image: game-catalog-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: http
        livenessProbe:
          httpGet:
            path: /games/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /games/ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: MONGODB_URI
          value: "mongodb://gameportal:password123@mongo-svc:27017/gameportal"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: game-catalog-svc
  namespace: gameportal
  labels:
    app: game-catalog
spec:
  selector:
    app: game-catalog
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: game-catalog-hpa
  namespace: gameportal
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: game-catalog
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70