apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: price-comparison-hpa
  namespace: gameportal
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: price-comparison
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70